# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				chicken = true
				bee = true
				donkey = true
				cow = true
				chest_minecart = true
				magma_cube = true
				pig = true
				skeleton = true
				iron_golem = true
				bat = true
				zombified_piglin = true
				piglin = true
				rabbit = true
				zombie = true
				ghast = true
				sheep = true
				player = true
				item = true
				villager = true
				salmon = true
				polar_bear = true
				strider = true
				horse = true
				phantom = true
				ender_dragon = true
				glow_squid = true
				witch = true
				glow_item_frame = false
				squid = true
				spider = true
				creeper = true
				enderman = true

			[light_sources.settings.entities.betternether]
				firefly = true
				hydrogen_jellyfish = true
				skull = true

			[light_sources.settings.entities.betterend]
				shadow_walker = true

